/* ═══════════════════════════════════════════════════════════════
   ENGINEERING OS, CENTRAL DATA SOURCE
   Single source of truth. All modules read from here.
   No fake data, no invented metrics, no fabricated credentials.
   ═══════════════════════════════════════════════════════════════ */

/* ── Projects ─────────────────────────────────────────────────── */
export const PROJECTS = [
  {
    id: 'support-hub-ai',
    title: 'Support Hub AI',
    category: 'Web Application',
    color: '#10b981',
    stack: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'Socket.IO', 'WebRTC', 'JWT', 'Pinecone'],
    tagline: 'AI-powered customer support platform with real-time communication and RAG-based knowledge base.',
    github: 'https://github.com/shivchandarsah',
  },
  {
    id: 'bolts-army',
    title: 'Bolts Army',
    category: 'Web Application',
    color: '#f59e0b',
    stack: ['React.js', 'Node.js', 'Express.js', 'MySQL', 'Sequelize', 'JWT'],
    tagline: 'Business management CRM with role-based access, inventory tracking and reporting.',
    github: 'https://github.com/shivchandarsah',
  },
  {
    id: 'sikshamantra',
    title: 'Sikshamantra',
    category: 'Web Application',
    color: '#3b82f6',
    stack: ['React.js', 'Node.js', 'Express.js', 'MongoDB', 'JWT'],
    tagline: 'Full-stack learning management system with course builder and student tracking.',
    github: 'https://github.com/shivchandarsah/Sikshamantra',
  },
  {
    id: 'smartinvoice',
    title: 'SmartInvoice',
    category: 'Web Application',
    color: '#10b981',
    stack: ['Vue.js', 'Node.js', 'Express.js', 'MongoDB'],
    tagline: 'Full-stack invoicing solution with PDF export, client management and payment tracking.',
    github: 'https://github.com/shivchandarsah/SmartInvoice',
  },
];

/* ── Architecture per project ─────────────────────────────────── */
export const ARCHITECTURES = {
  'support-hub-ai': {
    nodes: [
      { id: 'client',    label: 'Client Browser', x: 50,  y: 8,  color: '#3b82f6', type: 'client',
        detail: { title: 'Client, React.js', tech: ['React.js', 'JavaScript', 'HTML5', 'CSS3'], responsibilities: ['User interface', 'Real-time chat UI', 'Video call interface', 'Dashboard views'], notes: 'SPA served statically. Communicates with API via REST and Socket.IO for live events.' }},
      { id: 'frontend',  label: 'React Frontend', x: 50,  y: 22, color: '#61dafb', type: 'frontend',
        detail: { title: 'Frontend Layer', tech: ['React.js', 'Socket.IO Client', 'WebRTC API'], responsibilities: ['Component rendering', 'Socket.IO event handling', 'WebRTC peer connection management', 'JWT token storage'], notes: 'Manages socket room subscriptions and peer-to-peer media negotiation.' }},
      { id: 'api',       label: 'Express API',    x: 50,  y: 38, color: '#84cc16', type: 'backend',
        detail: { title: 'Express REST API', tech: ['Node.js', 'Express.js'], responsibilities: ['Route handling', 'Request validation', 'Middleware orchestration', 'Error handling'], notes: 'Stateless REST endpoints. Auth middleware runs before every protected route.' }},
      { id: 'auth',      label: 'JWT Auth',       x: 20,  y: 53, color: '#f59e0b', type: 'auth',
        detail: { title: 'JWT Authentication & RBAC', tech: ['JWT', 'bcrypt'], responsibilities: ['Token generation & verification', 'Role-based access control', 'Protected route middleware', 'Session management'], security: ['Tokens signed with secret', 'Role claims in payload', 'Middleware on all protected routes'], notes: 'Roles: admin, agent, customer. Each role sees a different dashboard.' }},
      { id: 'socket',    label: 'Socket.IO',      x: 80,  y: 53, color: '#a78bfa', type: 'realtime',
        detail: { title: 'Socket.IO Real-time Engine', tech: ['Socket.IO', 'Node.js'], responsibilities: ['Real-time chat delivery', 'Presence indicators', 'Room management', 'Event broadcasting'], notes: 'Rooms scoped per support ticket. Agents join ticket rooms. Customers connect on ticket open.' }},
      { id: 'services',  label: 'Services',       x: 50,  y: 65, color: '#10b981', type: 'service',
        detail: { title: 'Business Logic Services', tech: ['Node.js'], responsibilities: ['Ticket management', 'AI response generation', 'User management', 'Knowledge base queries'], notes: 'Service layer decouples controllers from data access. Each service owns its domain.' }},
      { id: 'rag',       label: 'RAG / Pinecone', x: 80,  y: 78, color: '#6366f1', type: 'ai',
        detail: { title: 'RAG, Retrieval Augmented Generation', tech: ['Pinecone', 'Vector Embeddings'], responsibilities: ['Knowledge base storage', 'Semantic search', 'Context retrieval for AI responses'], notes: 'Documents embedded as vectors. On support query, top-k similar chunks retrieved and passed to response generator.' }},
      { id: 'database',  label: 'MongoDB',        x: 20,  y: 78, color: '#47a248', type: 'database',
        detail: { title: 'MongoDB Database', tech: ['MongoDB', 'Mongoose ODM'], responsibilities: ['User data', 'Ticket data', 'Message history', 'Agent profiles'], notes: 'Collections: users, tickets, messages. Mongoose schemas enforce structure and run pre-save hooks for password hashing.' }},
    ],
    edges: [
      { from: 'client',   to: 'frontend' },
      { from: 'frontend', to: 'api' },
      { from: 'frontend', to: 'socket' },
      { from: 'api',      to: 'auth' },
      { from: 'api',      to: 'services' },
      { from: 'socket',   to: 'services' },
      { from: 'services', to: 'database' },
      { from: 'services', to: 'rag' },
    ],
  },

  'bolts-army': {
    nodes: [
      { id: 'client',   label: 'Client Browser', x: 50,  y: 8,  color: '#3b82f6', type: 'client',
        detail: { title: 'Client, React.js', tech: ['React.js', 'JavaScript'], responsibilities: ['Dashboard UI', 'Inventory views', 'Invoice management', 'Role-specific screens'] }},
      { id: 'frontend', label: 'React Frontend', x: 50,  y: 22, color: '#61dafb', type: 'frontend',
        detail: { title: 'Frontend, React.js', tech: ['React.js'], responsibilities: ['Component rendering', 'JWT token handling', 'Protected route guards', 'API calls via fetch'] }},
      { id: 'api',      label: 'Express API',    x: 50,  y: 38, color: '#84cc16', type: 'backend',
        detail: { title: 'Express REST API', tech: ['Node.js', 'Express.js'], responsibilities: ['CRUD endpoints for inventory, invoices, users', 'Middleware stack', 'Input validation'] }},
      { id: 'auth',     label: 'JWT + RBAC',     x: 20,  y: 53, color: '#f59e0b', type: 'auth',
        detail: { title: 'JWT Authentication + RBAC', tech: ['JWT', 'bcrypt'], responsibilities: ['Authentication', 'Role-based access', 'Route protection'], security: ['Role claims in JWT', 'bcrypt password hashing', 'Protected endpoints'], notes: 'Roles: owner, manager, staff. Certain routes only accessible by specific roles.' }},
      { id: 'services', label: 'Services',       x: 80,  y: 53, color: '#10b981', type: 'service',
        detail: { title: 'Business Logic Services', tech: ['Node.js'], responsibilities: ['Inventory logic', 'Invoice generation', 'Reporting calculations', 'User management'] }},
      { id: 'orm',      label: 'Sequelize ORM',  x: 50,  y: 68, color: '#52b0e7', type: 'orm',
        detail: { title: 'Sequelize ORM', tech: ['Sequelize', 'Node.js'], responsibilities: ['Model definitions', 'Query building', 'Migrations', 'Associations'], notes: 'Models: User, Product, Invoice, InvoiceItem. Associations enforce relational integrity.' }},
      { id: 'database', label: 'MySQL',          x: 50,  y: 83, color: '#4479a1', type: 'database',
        detail: { title: 'MySQL Database', tech: ['MySQL'], responsibilities: ['Relational data storage', 'Transaction support', 'Joins across entities'], notes: 'Relational structure suits business data: invoices reference products, products reference categories.' }},
    ],
    edges: [
      { from: 'client',   to: 'frontend' },
      { from: 'frontend', to: 'api' },
      { from: 'api',      to: 'auth' },
      { from: 'api',      to: 'services' },
      { from: 'services', to: 'orm' },
      { from: 'orm',      to: 'database' },
    ],
  },

  'sikshamantra': {
    nodes: [
      { id: 'client',   label: 'Client Browser', x: 50, y: 8,  color: '#3b82f6', type: 'client',
        detail: { title: 'Client, React.js', tech: ['React.js'], responsibilities: ['Course catalogue', 'Lesson viewer', 'Student dashboard', 'Instructor tools'] }},
      { id: 'frontend', label: 'React Frontend', x: 50, y: 25, color: '#61dafb', type: 'frontend',
        detail: { title: 'Frontend, React.js', tech: ['React.js', 'JavaScript'], responsibilities: ['SPA routing', 'Protected routes', 'Course content rendering', 'Progress tracking UI'] }},
      { id: 'api',      label: 'Express API',    x: 50, y: 45, color: '#84cc16', type: 'backend',
        detail: { title: 'Express REST API', tech: ['Node.js', 'Express.js'], responsibilities: ['Course CRUD', 'Enrollment management', 'Auth endpoints', 'Progress endpoints'] }},
      { id: 'auth',     label: 'JWT Auth',       x: 25, y: 65, color: '#f59e0b', type: 'auth',
        detail: { title: 'JWT Authentication', tech: ['JWT', 'bcrypt'], responsibilities: ['Student / instructor auth', 'Role separation', 'Token verification middleware'] }},
      { id: 'database', label: 'MongoDB',        x: 75, y: 65, color: '#47a248', type: 'database',
        detail: { title: 'MongoDB', tech: ['MongoDB', 'Mongoose'], responsibilities: ['User profiles', 'Course data', 'Enrollment records', 'Lesson content'], notes: 'Document model suits nested course → module → lesson hierarchy.' }},
    ],
    edges: [
      { from: 'client',   to: 'frontend' },
      { from: 'frontend', to: 'api' },
      { from: 'api',      to: 'auth' },
      { from: 'api',      to: 'database' },
    ],
  },

  'smartinvoice': {
    nodes: [
      { id: 'client',   label: 'Client Browser', x: 50, y: 8,  color: '#3b82f6', type: 'client',
        detail: { title: 'Client, Vue.js', tech: ['Vue.js'], responsibilities: ['Invoice creation UI', 'Client management', 'Payment status views', 'PDF preview'] }},
      { id: 'frontend', label: 'Vue.js Frontend', x: 50, y: 25, color: '#42b883', type: 'frontend',
        detail: { title: 'Frontend, Vue.js', tech: ['Vue.js', 'JavaScript'], responsibilities: ['Reactive form handling', 'Invoice item calculation', 'PDF generation trigger', 'API communication'] }},
      { id: 'api',      label: 'Express API',     x: 50, y: 45, color: '#84cc16', type: 'backend',
        detail: { title: 'Express REST API', tech: ['Node.js', 'Express.js'], responsibilities: ['Invoice CRUD', 'Client CRUD', 'Payment status updates', 'Report endpoints'] }},
      { id: 'database', label: 'MongoDB',         x: 50, y: 68, color: '#47a248', type: 'database',
        detail: { title: 'MongoDB', tech: ['MongoDB', 'Mongoose'], responsibilities: ['Invoice storage', 'Client records', 'Payment history'], notes: 'Flexible document model suits varied invoice line-item structures.' }},
    ],
    edges: [
      { from: 'client',   to: 'frontend' },
      { from: 'frontend', to: 'api' },
      { from: 'api',      to: 'database' },
    ],
  },
};

/* ── Project X-Ray layers ─────────────────────────────────────── */
export const XRAY_LAYERS = {
  'support-hub-ai': [
    { id: 'ui',         label: 'UI Layer',          icon: '🖥️',  color: '#61dafb',
      tech: ['React.js', 'CSS3'],
      what: 'The React frontend renders the customer and agent dashboards. Customers see a chat widget and ticket list. Agents see a full inbox, ticket details, and the AI-suggested response panel.',
      decisions: 'React chosen for its component model, each chat message, ticket card and suggestion chip is a reusable component.',
      security: 'JWT stored in memory (not localStorage) to prevent XSS exposure.' },
    { id: 'api',        label: 'REST API',           icon: '🔌',  color: '#84cc16',
      tech: ['Express.js', 'Node.js'],
      what: 'Stateless Express API handles all CRUD operations. Routes are grouped by domain: /api/auth, /api/tickets, /api/messages, /api/users.',
      decisions: 'Express chosen for its minimal footprint and excellent middleware ecosystem on Node.js.',
      security: 'Auth middleware validates JWT on every protected route before any controller runs.' },
    { id: 'auth',       label: 'Authentication',     icon: '🔐',  color: '#f59e0b',
      tech: ['JWT', 'bcrypt'],
      what: 'JWT-based stateless authentication. Passwords hashed with bcrypt before storage. Role claims (admin / agent / customer) embedded in token payload.',
      decisions: 'JWT chosen over sessions to keep the API stateless and horizontally scalable.',
      security: 'bcrypt work factor 10. Tokens expire after configurable TTL. RBAC enforced per route.' },
    { id: 'realtime',   label: 'Real-time Layer',    icon: '⚡',  color: '#a78bfa',
      tech: ['Socket.IO', 'WebRTC'],
      what: 'Socket.IO handles text messaging and presence. WebRTC handles peer-to-peer video calls via signalling through the Socket.IO server.',
      decisions: 'Socket.IO over raw WebSocket for auto-reconnect and room support. WebRTC for true P2P video to reduce server bandwidth.',
      security: 'Socket handshake validates JWT before allowing room joins.' },
    { id: 'rag',        label: 'AI / RAG Engine',    icon: '🤖',  color: '#6366f1',
      tech: ['Pinecone', 'Vector Embeddings'],
      what: 'Support documents are embedded as vectors and stored in Pinecone. On incoming support query, top-k semantically similar chunks are retrieved and injected into the response context.',
      decisions: 'RAG chosen over fine-tuning, allows knowledge base updates without retraining.',
      security: 'Knowledge base only contains public support documentation. No customer data embedded.' },
    { id: 'database',   label: 'Database',           icon: '🗄️',  color: '#47a248',
      tech: ['MongoDB', 'Mongoose'],
      what: 'MongoDB stores users, tickets, and messages. Mongoose schemas enforce structure and run pre-save hooks (e.g. password hashing on user save).',
      decisions: 'MongoDB chosen for flexible ticket metadata, different ticket types have different fields.',
      security: 'Sensitive fields (password) never returned in API responses via Mongoose select: false.' },
  ],

  'bolts-army': [
    { id: 'ui',         label: 'UI Layer',            icon: '🖥️', color: '#61dafb',
      tech: ['React.js'],
      what: 'React dashboard with role-specific views. Owner sees full financials. Manager sees inventory and orders. Staff sees their assigned tasks.',
      decisions: 'React for its mature ecosystem and component reusability across role-specific dashboards.',
      security: 'Frontend route guards prevent navigation to unauthorised sections.' },
    { id: 'api',        label: 'REST API',             icon: '🔌', color: '#84cc16',
      tech: ['Express.js', 'Node.js'],
      what: 'Express API with routes for /auth, /products, /invoices, /users, /reports. Role middleware injected per route group.',
      decisions: 'Clean route/controller/service separation keeps business logic out of route handlers.',
      security: 'Input sanitised at controller level before hitting the service layer.' },
    { id: 'auth',       label: 'JWT + RBAC',           icon: '🔐', color: '#f59e0b',
      tech: ['JWT', 'bcrypt'],
      what: 'JWT auth with role-based access control. Three roles: owner, manager, staff. Each role has a defined set of allowed operations.',
      decisions: 'RBAC in middleware rather than in business logic, keeps role checks at the entry point.',
      security: 'bcrypt for passwords. JWT role claim validated on every request.' },
    { id: 'orm',        label: 'Sequelize ORM',        icon: '🔗', color: '#52b0e7',
      tech: ['Sequelize'],
      what: 'Sequelize models map to MySQL tables. Associations (hasMany, belongsTo) define invoice → line items, products → categories.',
      decisions: 'ORM chosen for type-safe queries and migration support over raw SQL.',
      security: 'Parameterised queries via Sequelize prevent SQL injection.' },
    { id: 'database',   label: 'MySQL Database',       icon: '🗄️', color: '#4479a1',
      tech: ['MySQL'],
      what: 'Relational MySQL for business data. Invoices reference products. Products reference categories. Foreign key constraints maintain integrity.',
      decisions: 'MySQL over MongoDB because business data is highly relational, invoices, line items, products, users all join.',
      security: 'DB user has only SELECT/INSERT/UPDATE/DELETE privileges, no DROP or schema access.' },
  ],

  'sikshamantra': [
    { id: 'ui',       label: 'UI Layer',      icon: '🖥️', color: '#61dafb',
      tech: ['React.js'],
      what: 'React SPA with views for course catalogue, lesson player, student progress and instructor course builder.',
      decisions: 'React for component reusability, course cards, lesson items, and progress bars are shared across student/instructor views.' },
    { id: 'api',      label: 'REST API',      icon: '🔌', color: '#84cc16',
      tech: ['Express.js', 'Node.js'],
      what: 'Express API serving courses, users, enrollments and progress data. Open-source team project (team of 5).',
      decisions: 'RESTful design with clear resource-based URLs for maintainability across the team.' },
    { id: 'auth',     label: 'JWT Auth',      icon: '🔐', color: '#f59e0b',
      tech: ['JWT', 'bcrypt'],
      what: 'Two roles: student and instructor. JWT middleware validates token on every protected route.',
      security: 'Passwords hashed with bcrypt. Tokens carry role and userId for downstream authorisation.' },
    { id: 'database', label: 'MongoDB',       icon: '🗄️', color: '#47a248',
      tech: ['MongoDB', 'Mongoose'],
      what: 'MongoDB stores courses (with nested module and lesson sub-documents), users, and enrollments.',
      decisions: 'Document model suits the nested course → module → lesson hierarchy naturally.' },
  ],

  'smartinvoice': [
    { id: 'ui',       label: 'UI Layer',      icon: '🖥️', color: '#42b883',
      tech: ['Vue.js'],
      what: 'Vue.js frontend with reactive invoice builder. Line items auto-calculate totals. PDF generation triggered from UI.',
      decisions: 'Vue.js for full-stack alignment and its reactive data binding, ideal for form-heavy invoicing UI.' },
    { id: 'api',      label: 'REST API',      icon: '🔌', color: '#84cc16',
      tech: ['Express.js', 'Node.js'],
      what: 'Express API with invoice CRUD, client management endpoints, and report aggregations.',
      decisions: 'REST API decouples the Vue frontend from data, allows potential mobile client in future.' },
    { id: 'database', label: 'MongoDB',       icon: '🗄️', color: '#47a248',
      tech: ['MongoDB', 'Mongoose'],
      what: 'MongoDB stores invoices with embedded line items. Client documents store contact and payment history.',
      decisions: 'Flexible schema handles varying numbers of line items per invoice without schema migrations.' },
  ],
};

/* ── Knowledge Graph nodes ─────────────────────────────────────── */
export const GRAPH_NODES = [
  /* Projects */
  { id: 'support-hub-ai', label: 'Support Hub AI',  type: 'project',  color: '#10b981', x: 320, y: 200 },
  { id: 'bolts-army',     label: 'Bolts Army',       type: 'project',  color: '#f59e0b', x: 100, y: 320 },
  { id: 'sikshamantra',   label: 'Sikshamantra',     type: 'project',  color: '#3b82f6', x: 540, y: 320 },
  { id: 'smartinvoice',   label: 'SmartInvoice',     type: 'project',  color: '#10b981', x: 320, y: 420 },

  /* Technologies */
  { id: 'react',     label: 'React.js',     type: 'tech',    color: '#61dafb', x: 180, y: 100 },
  { id: 'vue',       label: 'Vue.js',       type: 'tech',    color: '#42b883', x: 460, y: 100 },
  { id: 'node',      label: 'Node.js',      type: 'tech',    color: '#84cc16', x: 320, y: 60  },
  { id: 'express',   label: 'Express.js',   type: 'tech',    color: '#e2e8f0', x: 90,  y: 190 },
  { id: 'mongodb',   label: 'MongoDB',      type: 'tech',    color: '#47a248', x: 550, y: 190 },
  { id: 'mysql',     label: 'MySQL',        type: 'tech',    color: '#4479a1', x: 50,  y: 430 },
  { id: 'socket',    label: 'Socket.IO',    type: 'tech',    color: '#a78bfa', x: 200, y: 280 },
  { id: 'webrtc',    label: 'WebRTC',       type: 'tech',    color: '#f55f00', x: 420, y: 280 },
  { id: 'jwt',       label: 'JWT Auth',     type: 'tech',    color: '#f59e0b', x: 320, y: 310 },
  { id: 'pinecone',  label: 'RAG/Pinecone', type: 'tech',    color: '#6366f1', x: 480, y: 420 },
  { id: 'sequelize', label: 'Sequelize',    type: 'tech',    color: '#52b0e7', x: 150, y: 460 },
];

export const GRAPH_EDGES = [
  { from: 'support-hub-ai', to: 'react'     },
  { from: 'support-hub-ai', to: 'node'      },
  { from: 'support-hub-ai', to: 'express'   },
  { from: 'support-hub-ai', to: 'mongodb'   },
  { from: 'support-hub-ai', to: 'socket'    },
  { from: 'support-hub-ai', to: 'webrtc'    },
  { from: 'support-hub-ai', to: 'jwt'       },
  { from: 'support-hub-ai', to: 'pinecone'  },
  { from: 'bolts-army',     to: 'react'     },
  { from: 'bolts-army',     to: 'node'      },
  { from: 'bolts-army',     to: 'express'   },
  { from: 'bolts-army',     to: 'mysql'     },
  { from: 'bolts-army',     to: 'jwt'       },
  { from: 'bolts-army',     to: 'sequelize' },
  { from: 'sikshamantra',   to: 'react'     },
  { from: 'sikshamantra',   to: 'node'      },
  { from: 'sikshamantra',   to: 'express'   },
  { from: 'sikshamantra',   to: 'mongodb'   },
  { from: 'sikshamantra',   to: 'jwt'       },
  { from: 'smartinvoice',   to: 'vue'       },
  { from: 'smartinvoice',   to: 'node'      },
  { from: 'smartinvoice',   to: 'express'   },
  { from: 'smartinvoice',   to: 'mongodb'   },
];

/* ── Engineering Decisions ─────────────────────────────────────── */
export const DECISIONS = [
  {
    id: 1,
    project: 'Support Hub AI',
    title: 'Why Socket.IO over raw WebSocket?',
    problem: 'Real-time bidirectional communication was needed for the support chat, messages must arrive instantly for both customer and agent.',
    options: ['Raw WebSocket', 'Socket.IO', 'HTTP Long Polling', 'Server-Sent Events'],
    chosen: 'Socket.IO',
    reasons: [
      'Automatic reconnection on disconnect, critical for support continuity',
      'Room-based architecture maps perfectly to support tickets',
      'Event-based API is cleaner than raw message parsing',
      'Fallback to long-polling for environments that block WebSocket',
      'Works natively with Node.js / Express',
    ],
    tradeoffs: 'Socket.IO adds ~60KB client bundle vs raw WebSocket. Acceptable given the reliability benefits.',
  },
  {
    id: 2,
    project: 'Support Hub AI',
    title: 'Why RAG over direct prompting?',
    problem: 'The support knowledge base contains product-specific information that a general LLM would not know. Answers must be grounded in actual documentation.',
    options: ['Direct LLM prompting', 'Fine-tuning', 'RAG (Retrieval Augmented Generation)', 'Static FAQ'],
    chosen: 'RAG with Pinecone',
    reasons: [
      'Knowledge base can be updated without retraining a model',
      'Answers are grounded in retrieved documents, reduces hallucination',
      'Pinecone vector search is fast and scalable',
      'No ongoing fine-tuning cost',
    ],
    tradeoffs: 'Retrieval quality depends on embedding quality and chunk size. Requires careful document preprocessing.',
  },
  {
    id: 3,
    project: 'Bolts Army',
    title: 'Why MySQL over MongoDB?',
    problem: 'The CRM manages invoices, products, clients, and payments, all of which have strict relationships and require consistent data integrity.',
    options: ['MongoDB', 'MySQL', 'PostgreSQL', 'SQLite'],
    chosen: 'MySQL',
    reasons: [
      'Invoices reference products, foreign key constraints enforce integrity',
      'Financial data benefits from ACID transactions',
      'Relational joins are natural for reporting (invoice totals, product summaries)',
      'Team had stronger MySQL experience at the time',
    ],
    tradeoffs: 'Schema migrations require more planning than MongoDB. Fixed schema means less flexibility for future fields.',
  },
  {
    id: 4,
    project: 'Bolts Army',
    title: 'Why Sequelize ORM?',
    problem: 'Writing raw SQL for all CRUD operations would be verbose and error-prone. Needed a way to model relationships and run safe parameterised queries.',
    options: ['Raw SQL', 'Sequelize', 'Knex.js', 'Prisma'],
    chosen: 'Sequelize',
    reasons: [
      'Mature ORM with strong MySQL support',
      'Model associations (hasMany, belongsTo) map cleanly to invoice → line items',
      'Built-in migration system for schema evolution',
      'Parameterised queries prevent SQL injection by default',
    ],
    tradeoffs: 'Sequelize can be verbose. Prisma would offer better TypeScript support, but the project used plain JavaScript.',
  },
  {
    id: 5,
    project: 'Support Hub AI',
    title: 'Why JWT over sessions?',
    problem: 'Authentication state needed to be maintained across API requests. Sessions require server-side state storage; the goal was a stateless API.',
    options: ['Server sessions', 'JWT', 'OAuth', 'API keys'],
    chosen: 'JWT',
    reasons: [
      'Stateless, no session store needed, API scales horizontally',
      'Role claims embedded in token, no DB lookup on every request',
      'Works cleanly with REST architecture',
      'Easy to implement RBAC by reading token payload in middleware',
    ],
    tradeoffs: 'JWTs cannot be invalidated before expiry without a denylist. Mitigated by short expiry + refresh token pattern.',
  },
  {
    id: 6,
    project: 'SmartInvoice',
    title: 'Why Vue.js for a full-stack project?',
    problem: 'The invoicing UI needed reactive form handling, line item totals must update live as quantities and prices change.',
    options: ['React.js', 'Vue.js', 'Vanilla JS', 'Angular'],
    chosen: 'Vue.js',
    reasons: [
      'Two-way data binding (v-model) simplifies reactive form state for invoice line items',
      'Completing multiple full-stack projects demonstrates breadth',
      'Vue\'s progressive framework allows incremental adoption',
      'Smaller learning curve for the team members unfamiliar with React',
    ],
    tradeoffs: 'Smaller ecosystem than React. Some libraries available for React are not available for Vue.',
  },
];

/* ── Technical Challenges ─────────────────────────────────────── */
export const CHALLENGES = [
  {
    id: 1, category: 'Security', xp: 100,
    question: 'A user reports they can access admin routes after their role was downgraded. What is the most likely cause?',
    options: ['Database corruption', 'JWT not expiring, old token still valid with old role claim', 'CSS bug hiding the button', 'Browser cache issue'],
    correct: 1,
    explanation: 'JWT tokens embed the role claim at issuance time. If the token has not expired, the old role is still in the payload. The fix is to either shorten token TTL or implement a server-side token denylist / version check.',
  },
  {
    id: 2, category: 'Architecture', xp: 150,
    question: 'In the Support Hub AI architecture, why does the Socket.IO handshake validate the JWT before allowing room joins?',
    options: ['To reduce database queries', 'To ensure only authenticated users can receive or send real-time messages', 'To improve Socket.IO performance', 'To enable WebRTC connections'],
    correct: 1,
    explanation: 'Without JWT validation at the socket handshake, any unauthenticated client could connect and subscribe to ticket rooms, exposing support conversations. Authentication at the transport layer enforces security at every layer.',
  },
  {
    id: 3, category: 'Database', xp: 100,
    question: 'Bolts Army uses MySQL with Sequelize. A developer writes a raw string query instead of using the ORM. What security risk does this introduce?',
    options: ['Memory leak', 'SQL injection vulnerability', 'Connection pool exhaustion', 'Slower query performance'],
    correct: 1,
    explanation: 'Raw string queries constructed from user input are vulnerable to SQL injection. Sequelize\'s query methods use parameterised statements that safely escape user input. Always use ORM methods or explicitly parameterise raw queries.',
  },
  {
    id: 4, category: 'Backend', xp: 100,
    question: 'The Express API returns 401 Unauthorized on a protected route. What should you check first?',
    options: ['Database connection', 'JWT token, expired, malformed, or missing from request headers', 'CSS styling', 'MongoDB collection name'],
    correct: 1,
    explanation: 'A 401 from a protected Express route almost always means the auth middleware rejected the request. Check: is the token present in the Authorization header? Is it expired? Is it signed with the correct secret? Is the Bearer prefix included?',
  },
  {
    id: 5, category: 'Architecture', xp: 150,
    question: 'Why is the service layer (business logic) separate from the controller layer in these projects?',
    options: ['It is a framework requirement', 'Separation of concerns, controllers handle HTTP, services handle business logic', 'To use more files', 'For CSS organisation'],
    correct: 1,
    explanation: 'Separating controllers from services means business logic can be tested independently of HTTP. Controllers become thin, they validate input, call the service, and return the response. Services can be reused by different controllers (REST and Socket handlers both call the same service).',
  },
  {
    id: 6, category: 'Database', xp: 150,
    question: 'Support Hub AI uses MongoDB. Bolts Army uses MySQL. What was the primary factor driving this difference?',
    options: ['Cost difference', 'Data structure, flexible ticket metadata vs strict relational business data', 'Performance benchmarks', 'MongoDB does not support authentication'],
    correct: 1,
    explanation: 'Support tickets have varied, unpredictable metadata, MongoDB\'s flexible document model handles this naturally. Business data (invoices, products, clients) is highly relational with strict integrity requirements, MySQL with foreign keys and ACID transactions is the right tool.',
  },
  {
    id: 7, category: 'Security', xp: 200,
    question: 'A password is stored as plain text in the database. The database is breached. What is the immediate consequence?',
    options: ['Only the app data is exposed', 'All stored passwords are immediately readable, attackers can access the app and potentially other accounts where users reused passwords', 'Nothing, the app still works', 'Passwords are auto-encrypted by MySQL'],
    correct: 1,
    explanation: 'Plain text passwords mean a database breach directly exposes every user\'s password. bcrypt hashing means attackers must brute-force each hash individually. Always hash passwords with a slow algorithm (bcrypt, Argon2) before storage. Never store or log plain text passwords.',
  },
  {
    id: 8, category: 'Backend', xp: 100,
    question: 'What is the primary advantage of using RESTful API design with clear resource-based URLs?',
    options: ['Faster server performance', 'Predictability and consistency, developers can infer API behaviour from URL patterns', 'Smaller bundle size', 'Automatic authentication'],
    correct: 1,
    explanation: 'REST conventions (GET /users, POST /users, GET /users/:id, PUT /users/:id, DELETE /users/:id) are universally understood. Any developer joining the project can immediately understand what endpoints exist and what they do, reducing onboarding friction.',
  },
];

/* ── Engineering Lab configs ────────────────────────────────────── */
export const LAB_AUTH_STEPS = [
  { id: 'input',      label: 'User Input',       desc: 'User enters email and password in the login form.',          color: '#3b82f6' },
  { id: 'request',    label: 'HTTP Request',      desc: 'POST /api/auth/login, credentials sent over HTTPS.',        color: '#61dafb' },
  { id: 'validate',   label: 'Input Validation',  desc: 'Server validates email format and password presence.',        color: '#f59e0b' },
  { id: 'lookup',     label: 'User Lookup',       desc: 'Find user by email in database.',                            color: '#84cc16' },
  { id: 'bcrypt',     label: 'bcrypt Compare',    desc: 'Compare submitted password against stored bcrypt hash.',     color: '#a78bfa' },
  { id: 'token',      label: 'JWT Issued',        desc: 'Signed JWT created with userId, role, and expiry claim.',    color: '#10b981' },
  { id: 'response',   label: 'Response',          desc: 'Token returned to client. Client stores in memory.',         color: '#46e3b7' },
  { id: 'protected',  label: 'Protected Request', desc: 'Client sends JWT in Authorization: Bearer header.',          color: '#f05032' },
  { id: 'middleware', label: 'Auth Middleware',    desc: 'Server verifies token signature and expiry. Extracts role.', color: '#f59e0b' },
  { id: 'rbac',       label: 'RBAC Check',        desc: 'Role compared against required permissions for the route.',  color: '#6366f1' },
  { id: 'granted',    label: 'Access Granted',    desc: 'Controller runs. Data returned to authenticated user.',      color: '#10b981' },
];

export const LAB_API_METHODS = [
  { method: 'GET',    desc: 'Retrieve a resource. Safe and idempotent.',        example: 'GET /api/tickets',       statusCode: 200, color: '#10b981' },
  { method: 'POST',   desc: 'Create a new resource.',                            example: 'POST /api/tickets',      statusCode: 201, color: '#3b82f6' },
  { method: 'PUT',    desc: 'Replace an existing resource fully.',               example: 'PUT /api/tickets/:id',   statusCode: 200, color: '#f59e0b' },
  { method: 'DELETE', desc: 'Remove a resource.',                                example: 'DELETE /api/tickets/:id',statusCode: 200, color: '#ef4444' },
];

export const LAB_DB_OPS = [
  { op: 'INSERT', label: 'Create',  color: '#10b981', desc: 'Add a new document/row to the collection/table.' },
  { op: 'FIND',   label: 'Read',    color: '#3b82f6', desc: 'Query one or many documents matching a filter.' },
  { op: 'UPDATE', label: 'Update',  color: '#f59e0b', desc: 'Modify fields on an existing document/row.' },
  { op: 'DELETE', label: 'Delete',  color: '#ef4444', desc: 'Remove a document/row from the collection/table.' },
];
